<a href="https://colab.research.google.com/github/Nada-Naveesh/Tensorflow/blob/main/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#write a program to find the order and type of a tensor.
import tensorflow as tf
a=tf.constant(2)
b=tf.constant([1,2,3])
c=tf.constant([[1,2,3],[4,5,6]])
d=tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
print('Tensor-A =',a)
print('Tensor-B =',b)
print('Tensor-C =',c)
print('Tensor-D =',d)
print('Rank of tensor-a is ',tf.rank(a),'and it is a scalar.')
print('Rank of tensor-b is ',tf.rank(b),'and it is a vector.')
print('Rank of tensor-c is ',tf.rank(c),'and it is a matrix.')
print('Rank of tensor-d is ',tf.rank(d),'and it is a 3-D tensor.')

Tensor-A = tf.Tensor(2, shape=(), dtype=int32)
Tensor-B = tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Tensor-C = tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Tensor-D = tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)
Rank of tensor-a is  tf.Tensor(0, shape=(), dtype=int32) and it is a scalar.
Rank of tensor-b is  tf.Tensor(1, shape=(), dtype=int32) and it is a vector.
Rank of tensor-c is  tf.Tensor(2, shape=(), dtype=int32) and it is a matrix.
Rank of tensor-d is  tf.Tensor(3, shape=(), dtype=int32) and it is a 3-D tensor.


In [7]:
#Arithmetic, Comparative - element wise operations

import tensorflow as tf
a=tf.constant([[1,2,3],[4,5,6]])
b=tf.constant([[7,8,9],[10,11,12]])
print('Element in Tensor-A =', a)
print('Element in Tensor-B =', b)
print('Element wise sum of tensors=',tf.add(a,b))
print('Element wise difference betweeen two tensors =',tf.subtract(a,b))
print('Element wise product of two Tensors =',tf.multiply(a,b))
print('Element wise divisions of two tensors =',tf.divide(a,b))
print('Element wise power of  two tensors =', tf.pow(a,b))

#Comparative Operators

print('Check for the element wise equality of tensors :',tf.equal(a,b))
print('Check for the element wise not_equality of tensors :',tf.not_equal(a,b))
print('Check for the element wise greater value of tensors :',tf.greater(a,b))
print('Check for the element wise less value of tensors :',tf.less(a,b))


Element in Tensor-A = tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Element in Tensor-B = tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)
Element wise sum of tensors= tf.Tensor(
[[ 8 10 12]
 [14 16 18]], shape=(2, 3), dtype=int32)
Element wise difference betweeen two tensors = tf.Tensor(
[[-6 -6 -6]
 [-6 -6 -6]], shape=(2, 3), dtype=int32)
Element wise product of two Tensors = tf.Tensor(
[[ 7 16 27]
 [40 55 72]], shape=(2, 3), dtype=int32)
Element wise divisions of two tensors = tf.Tensor(
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]], shape=(2, 3), dtype=float64)
Element wise power of  two tensors = tf.Tensor(
[[          1         256       19683]
 [    1048576    48828125 -2118184960]], shape=(2, 3), dtype=int32)
Check for the element wise equality of tensors : tf.Tensor(
[[False False False]
 [False False False]], shape=(2, 3), dtype=bool)
Check for the element wise inequality of tensors : tf.Tensor(
[[ True  True  True]
 [ Tru

In [8]:
#write a program to find the value of activation functions.
#Sigmoid Function , Tanh Function ,ReLU Function

import tensorflow as tf
import numpy as np
x=np.array([0,-1.5,2,1])
print('sigmoid funtion value =',tf.sigmoid(x))
print('tanh function value =',tf.tanh(x))
print('ReLU function value =',tf.nn.relu(x))

sigmoid funtion value = tf.Tensor([0.5        0.18242552 0.88079708 0.73105858], shape=(4,), dtype=float64)
tanh function value = tf.Tensor([ 0.         -0.90514825  0.96402758  0.76159416], shape=(4,), dtype=float64)
ReLU function value = tf.Tensor([0. 0. 2. 1.], shape=(4,), dtype=float64)


### Activation Function

In the context of artificial neural networks, an **activation function** is a crucial component of an artificial neuron (or node). It determines whether a neuron should be 'activated' (fire) or not, based on the weighted sum of its inputs.

Here's a breakdown of its importance and common types:

**Purpose of Activation Functions:**

1.  **Introduce Non-linearity:** Without activation functions, a neural network would simply be a series of linear transformations. This means it would only be able to learn linear mappings from inputs to outputs, severely limiting its ability to solve complex problems. Activation functions introduce non-linearity, allowing the network to learn and approximate complex, non-linear relationships in data.
2.  **Determine Output:** The activation function takes the weighted sum of the inputs to a neuron and biases, and then produces an output that is passed to the next layer of neurons.
3.  **Provide Training Stability:** Some activation functions (like ReLU and its variants) help to mitigate issues like the vanishing gradient problem during training, allowing deeper networks to be trained more effectively.

**Common Types of Activation Functions:**

1.  **Sigmoid Function (Logistic Function):**
    *   **Formula:** `σ(x) = 1 / (1 + e^(-x))`
    *   **Output Range:** (0, 1)
    *   **Characteristics:** Smooth, differentiable, and often used in the output layer for binary classification problems (where the output needs to be a probability).
    *   **Drawbacks:** Prone to vanishing gradient problem for very large or very small inputs, and outputs are not zero-centered.

2.  **Tanh Function (Hyperbolic Tangent):**
    *   **Formula:** `tanh(x) = (e^x - e^(-x)) / (e^x + e^(-x))`
    *   **Output Range:** (-1, 1)
    *   **Characteristics:** Similar to sigmoid but outputs are zero-centered, which can make training easier for subsequent layers.
    *   **Drawbacks:** Still suffers from the vanishing gradient problem.

3.  **ReLU (Rectified Linear Unit):**
    *   **Formula:** `f(x) = max(0, x)`
    *   **Output Range:** [0, infinity)
    *   **Characteristics:** Simple, computationally efficient, and helps to alleviate the vanishing gradient problem. It's the most widely used activation function in hidden layers.
    *   **Drawbacks:** Suffers from the 'dying ReLU' problem, where neurons can become inactive if their input is always negative, causing their gradient to be zero.

4.  **Leaky ReLU:**
    *   **Formula:** `f(x) = max(0.01x, x)` (for x < 0, output is 0.01x; for x >= 0, output is x)
    *   **Output Range:** (-infinity, infinity)
    *   **Characteristics:** Addresses the 'dying ReLU' problem by allowing a small, non-zero gradient when the input is negative.

5.  **ELU (Exponential Linear Unit):**
    *   **Formula:** `f(x) = x` if `x >= 0`, and `f(x) = alpha * (e^x - 1)` if `x < 0`
    *   **Output Range:** (-alpha, infinity)
    *   **Characteristics:** Can lead to faster learning and better performance than ReLU by producing negative outputs, which helps to push the mean activation closer to zero.

6.  **Softmax Function:**
    *   **Formula:** `softmax(x_i) = e^(x_i) / sum(e^x_j)`
    *   **Output Range:** (0, 1) for each output, and the sum of all outputs is 1.
    *   **Characteristics:** Typically used in the output layer of a multi-class classification neural network. It converts a vector of arbitrary real values into a probability distribution.

Choosing the right activation function depends on the specific task and network architecture, but ReLU and its variants are generally good starting points for hidden layers.

In [24]:
#write a program to implement logic gate using MP Neuron model.


import numpy as np
x=np.array([[0,0],[0,1],[1,0],[1,1]])
w=np.array([1,0])
yact=np.array([0,0,0,1])
print('Input matrix:', x)
print('Weight matrix:', w)
print('Actual output matrix:', yact)
y =np.dot(x,w.T)
print('Total input :', y)
for i in range(len(y)):
  if(y[i]>=2):
    y[i]=1
  else:
    y[i]=0
print('Predicted output :', y)
print('check for the correctness of predicted output :\n', np.allclose(y,yact))

Input matrix: [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Weight matrix: [1 0]
Actual output matrix: [0 0 0 1]
Total input : [0 0 1 1]
Predicted output : [0 0 0 0]
check for the correctness of predicted output :
 False
